ministryofjustice/laa-criminal-applications-datastore

- app/api/datastore/base.rb
- app/api/datastore/root.rb
- app/api/datastore/v2/applications.rb
- app/models/crime_application.rb
- app/services/operations/create_application.rb
- db/migrate/20221130115736_create_crime_applications.rb
- db/schema.rb
- spec/api/datastore/v2/applications_spec.rb
- spec/models/crime_application_spec.rb
Adds V2 endpoint for storing an application in the postgres datastore.
CRIMAP-219-v2-api-create-application
Sets the database ID to that in the JSON payload. As with the V1 api, returns a 400 error if a record with that ID already exists.
Currently only the unit test are writing to the test DB. Happy to review this approach if others would prefer us to do it differently.
> CRIMAP-219 Create via v2 api and store in postgres

- .rubocop.yml
- app/api/datastore/entities/crime_application.rb
- app/api/datastore/v2/applications.rb
- app/models/crime_application.rb
- app/services/operations/list_applications.rb
- db/migrate/20221208165036_add_status_attributes_and_indexes_to_crime_applications.rb
- db/schema.rb
- spec/api/datastore/v2/list_applications_spec.rb
- spec/models/crime_application_spec.rb
- spec/services/operations/list_applications_spec.rb
Adds filtering by status and sorting to list applications.
Status can filter by "submitted" or "returned". If no status param is specified, all applications are shown.
Sort order can be specified. Default is descending. When status is submitted, or not specified, sort is based on submitted_at. When status is returned, sort is based on returned_at.
[CRIMAP-219](https://dsdmoj.atlassian.net/browse/CRIMAP-219)
I'd like to propose that submitted_at and status should not be specified by apply on create. Instead status, submitted_at, returned_at etc should be the responsibility of the datastore. The data store will return these attributes in the document as per the schema.
> CRIMAP-219 List applications filter and sort by status.

- app/api/datastore/v2/searches.rb
- app/models/search_filter.rb
- spec/api/datastore/v2/searches/filter_by_application_id_spec.rb
- spec/api/datastore/v2/searches/filter_by_submitted_at_spec.rb
- spec/api/datastore/v2/searches/search_by_name_and_reference_spec.rb
Searches can be filtered by submitted_at.
Uses two independent search params "submitted_before" and "submitted_after".
> Crimre 83 filter by submitted at

- Gemfile.lock
- app/api/datastore/v2/applications.rb
- app/models/crime_application.rb
- app/services/operations/list_applications.rb
- spec/api/datastore/v2/list_applications_spec.rb
Apply requires filtering by office code. All requests to GET /applications will include, in addition to the `status` of the application, the `office_code` of the provider that submitted it.
I've done the filtering with a scope based on the JSON stored in the `application` DB field. This will unlock additional functionality on Apply side.
I'm sure there are better ways to do this, as this probably is slow, specially without an index. Please feel free to change this to virtual attributes or whatever if that's better.
https://dsdmoj.atlassian.net/browse/CRIMAP-249
Apply is already submitting payloads containing the `office_code`.
> Implement scope by office code in list endpoint

- app/api/datastore/entities/search_result.rb
- app/api/datastore/v2/searches.rb
- app/models/search_filter.rb
- spec/api/datastore/v2/searches/filter_by_application_id_spec.rb
- spec/models/search_filter_spec.rb
Adds `application_id_not_in` filter to search.
Changes `application_ids` filter to `application_id_in`.
[CRIMRE-118](https://dsdmoj.atlassian.net/browse/CRIMRE-118)
Reviewers need to be able filter out assigned applications from the search.
> CRIMRE-118 add filter by 'application id not in' to search.

- Gemfile.lock
Schema will start requiring the newly added legal representative details, on application submissions from Apply.
https://dsdmoj.atlassian.net/browse/CRIMAP-224
> Bump schemas gem (legal rep details)

- app/api/datastore/v2/searches.rb
- app/models/search_filter.rb
- spec/api/datastore/v2/searches/filter_by_date_of_birth_spec.rb
- spec/models/search_filter_spec.rb
Adds applicant date of birth to search filter.
[CRIMRE-126](https://dsdmoj.atlassian.net/browse/CRIMRE-126)
I've not added an index for applicant_date_of_birth yet, as I wonder if DOB should become part of the text search instead of having a separate filter.
[CRIMRE-126]: https://dsdmoj.atlassian.net/browse/CRIMRE-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-126-filter-by-applicant-date

- Gemfile.lock
- app/models/crime_application.rb
- lib/tasks/misc.rake
The schemas gem has been updated to introduce the new offence dates format. Additionally the provider details struct has been made stricter (the schema was already enforcing this on submission).
Sadly current submitted applications are not compatible with the new data structures.
A couple of handy rake tasks are provided, to be run (just once really, can be removed at a later commit) and update the applications.
To be able to do this more easily making use of active record, temporarily the `application` attribute has been removed from the `attr_readonly` declaration.
More context here:
https://mojdt.slack.com/archives/C03JS4V9TPU/p1673530745265879
https://dsdmoj.atlassian.net/browse/CRIMAP-251
The removal of the `attr_readonly` is only temporary to be able to run the rake tasks. Can be …
> Update schema and add migration rake tasks

- Gemfile.lock
Ideally to synchronise with a deployment of Apply incorporating the new provider email attribute to the submitted applications.
It includes these changes to the schemas gem:
- Add provider email to the schema https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/commit/8f635e523435a307769970f33bc33efba821f9bd
- Remove required status attribute on submitted applications https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/commit/65f7b0b1f9807181fe48eb7a50ab657081c74bf0
Partially related to:
https://dsdmoj.atlassian.net/browse/CRIMAP-121
> Bump schemas gem

- app/api/datastore/base.rb
- app/api/datastore/root.rb
- app/api/datastore/v2/reviewing.rb
- app/api/datastore/v2/searches.rb
- app/lib/errors.rb
- app/lib/types.rb
- app/models/crime_application.rb
- app/models/return_details.rb
- app/services/operations/return_application.rb
- db/migrate/20230120124639_create_return_details.rb
- db/schema.rb
- spec/api/datastore/v2/reviewing/return_application_spec.rb
- spec/api/datastore/v2/searches/filter_by_status_spec.rb
- spec/services/operations/list_applications_spec.rb
- spec/services/operations/return_application_spec.rb
Adds application return endpoint. Put request to: applications/:id/return
idempotent
Returns 409 if already returned, 404 if the application cannot be found.
[CRIMRE-52](https://dsdmoj.atlassian.net/browse/CRIMRE-52)
An additional PR to exposed the return_details to the application json will follow.
I have namespaced the code 'reviewing' with a view to all review actions living here. (Although the endpoints themselves remain resource based.)
This pattern could be followed by adding the following namespaces:
- Reviewing
- Applying
- Searching
- Reporting
[CRIMRE-52]: https://dsdmoj.atlassian.net/browse/CRIMRE-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-52-add-application-return

- Gemfile.lock
- app/api/datastore/entities/crime_application.rb
- app/api/datastore/entities/return_details.rb
- app/api/datastore/entities/search_result.rb
- app/api/datastore/v2/reviewing.rb
- app/lib/types.rb
- app/services/operations/return_application.rb
- db/migrate/20230125091219_tidy_review_attributes.rb
- db/schema.rb
- spec/api/datastore/v2/reviewing/return_application_spec.rb
- spec/api/datastore/v2/searches/filter_by_review_status_spec.rb
- spec/api/datastore/v2/searches/filter_by_submitted_at_spec.rb
- spec/services/operations/return_application_spec.rb
applications/:id/return responds with the updated application's json
Return details are included in the application json for returned crime applications .
[CRIMRE-52](https://dsdmoj.atlassian.net/browse/CRIMRE-52)
[CRIMRE-52]: https://dsdmoj.atlassian.net/browse/CRIMRE-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crimre 52 show return details for returned applications

- app/api/datastore/entities/sorting.rb
- app/api/datastore/v2/searches.rb
- app/models/sorting.rb
- app/services/operations/search.rb
- spec/api/datastore/v2/searches/sorting_spec.rb
- spec/models/sorting_spec.rb
Adds the ability to sort searches for review, this is first PR with the basic column sorts. Others will follow for the outstanding sortable columns.
[CRIMRE-142](https://dsdmoj.atlassian.net/browse/CRIMRE-142)
[CRIMRE-142]: https://dsdmoj.atlassian.net/browse/CRIMRE-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Crimre 142 add sort search

- Gemfile.lock
- app/models/crime_application.rb
- app/services/operations/create_application.rb
- app/services/operations/supersede_application.rb
- spec/api/datastore/v2/create_application_spec.rb
- spec/api/datastore/v2/list_applications_spec.rb
- spec/api/datastore/v2/reviewing/return_application_spec.rb
- spec/models/crime_application_spec.rb
- spec/services/operations/return_application_spec.rb
- spec/services/operations/supersede_application_spec.rb
On resubmission of a returned application, this new submission is technically a brand new application, but points to the returned one through an attribute `parent_id`.
With this information, when a resubmission (meaning  `parent_id` is not nil) is received and successfully validated and persisted, the “parent“ application is then marked as superseded, by changing its status.
Additionally in this PR some minor tweaks:
- shift the `submitted_at` attribute from the payload to the table column so both are always in sync.
- use an enum for the `status` attribute on the CrimeApplication records, so no longer need to have a separate presence/inclusion validation, and also we gain methods like `returned?` and scopes.
https://dsdmoj.atlassian.net/browse/CRIMAP-265
Note: in some places the statuses …
> CRIMAP-265 Supersede parent of resubmissions

- app/models/sorting.rb
- db/migrate/20230127125227_add_sort_indexes_to_crime_applications.rb
- db/schema.rb
- spec/models/sorting_spec.rb
Allow for sorting by applicant name and reference.
Adds reference, applicant first name, and applicant last names as virtual attributes for indexing.
[CRIMRE-143](https://dsdmoj.atlassian.net/browse/CRIMRE-143)
[CRIMRE-143]: https://dsdmoj.atlassian.net/browse/CRIMRE-143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-143 Sort by applicant_name and reference

- app/models/search_filter.rb
- spec/api/datastore/v2/searches/search_by_name_and_reference_spec.rb
Ensure text search vector and query use the same config.
[CRIMRE-164](https://dsdmoj.atlassian.net/browse/CRIMRE-164)
Testing locally would require updating pg_config to use a different dictionary to the one used for the vector. The revised code for the query from this PR was tested on staging via the console and confirmed to work.
[CRIMRE-164]: https://dsdmoj.atlassian.net/browse/CRIMRE-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-164 ensure search vector and query use same configuration

- .env.development
- Gemfile
- Gemfile.lock
- app/api/datastore/root.rb
- config/initializers/simple_jwt_auth.rb
- config/kubernetes/staging/deployment.tpl
Merging this will not enable JWT or change any functionality on the datastore, as it is not enabled yet (the line that would otherwise enable this is commented out on purpose for the easy testing in localhost).
Once the `auth :jwt` is enabled, it will make use of a little middleware introduced in the `simple-jwt-auth` gem to perform verification of the bearer token.
https://dsdmoj.atlassian.net/browse/CRIMAP-273
If wanted to test locally, a corresponding PR will be raised in the apply repo soon, in order to have an end to end, locally-testable demo.
> Prepare datastore for JWT auth

- app/api/datastore/root.rb
- config/kubernetes/staging/ingress.yml
Once merged, all API endpoints will require a JWT bearer token. There are corresponding PRs on Apply and Review repos for this as well.
Also once merged, the http basic auth will be disabled at the ingress on staging.
https://dsdmoj.atlassian.net/browse/CRIMAP-277
> Enable JWT authentication

- .env.development
- config/initializers/simple_jwt_auth.rb
With openssl >= 3.0.0 you need to have something in those secrets. Nil or empty string will produce an error.
With openssl < 3.0.0 a nil value will blow up but funnily enough not an empty string.
To avoid confusion and edge cases with the openssl version installed in each system, we set a default dummy value, so developers don't need to set their own in their `.local` files.
Also, tune the logger.
> Set a more sensible default for ENV variable

- db/migrate/20230216165844_set_default_review_status.rb
- db/schema.rb
- spec/api/datastore/v2/reviewing/complete_application_spec.rb
Add default value for review status
Add date sort indexes for review status
[CRIMRE-151](https://dsdmoj.atlassian.net/browse/CRIMRE-151)
Review will shortly uses review_status exclusively for all search and table views. This sets a default value and adds indexing for sorting by dates. 
[CRIMRE-151]: https://dsdmoj.atlassian.net/browse/CRIMRE-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add default value for review status

- .env.development
- Gemfile
- Gemfile.lock
- app/services/events/base_event.rb
- app/services/events/returned.rb
- app/services/events/submission.rb
- app/services/messaging/events_publisher.rb
- app/services/operations/create_application.rb
- app/services/operations/return_application.rb
- config/kubernetes/staging/deployment.tpl
- spec/api/datastore/v2/create_application_spec.rb
- spec/services/events/returned_spec.rb
- spec/services/events/submission_spec.rb
- spec/services/messaging/events_publisher_spec.rb
- spec/services/operations/return_application_spec.rb
- spec/support/shared_examples/events_shared_examples.rb
We now have an initial infrastructure created in the namespace, with an SNS topic that receives notifications, and an SQS queue where these notifications are sent (for now no filter).
Idea being, datastore will publish a series of events to the SNS topic, and then one or more SQS subscribe to this topic and each receives the notifications that matters to them, based on an event filter.
Each event has a name. Only 2 are created in this PR as an initial example. Also each event can implement its own message/payload. For now both are the same, they publish the whole application JSON. But some events might require only a few attributes so this is possible.
I've left previous code for job processor with `shoryuken` but I don't think we need that anymore and is an overkill for our needs. The …
> First incarnation of SNS events publishing

- app/services/messaging/events_publisher.rb
- spec/services/messaging/events_publisher_spec.rb
Some endpoints, like http, don't receive the message attributes, but they do receive the subject, so the event name can be added here for redundancy.
> Add SNS message subject

- Gemfile
- Gemfile.lock
- app/api/datastore/base.rb
- app/api/datastore/concerns/logging.rb
- app/lib/grape_logging/loggers/jwt_issuer.rb
- config/initializers/filter_parameter_logging.rb
- docker-compose.yml
- spec/lib/grape_logging/loggers/jwt_issuer_spec.rb
Logs to stdout so other systems can route these logs to final destinations for viewing and long-term archival. For example this is needed to see the logs in Kibana.
Also, added a few more PII parameters to the filter. These are also used by Sentry when reporting exceptions.
NOTE: not using `lograge` as we did on Apply because that gem is only for Rails/Rails API, but Datastore is Grape API. Using an alternative gem which is similar and also produce a `logstash` format.
It is easy to extend to log more stuff by implementing a `GrapeLogging::Loggers` class. For instance I've implemented one for logging the JWT issuer of the request: `lib/grape_logging/loggers/jwt_issuer.rb`
https://dsdmoj.atlassian.net/browse/CRIMAP-289
On local environments this new log stream to stdout can seen and tested …
> CRIMAP-289 Configure logging and filtering of PII

- config/kubernetes/staging/ingress.yml
As per documentation:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/migrating-from-live-1-domain-name.html
This is part of a broader ticket to use a custom domain for staging, however, for now this makes the service more resilient in case of cluster changes, until we have a production namespace and we set the proper final (and public) domains.
https://dsdmoj.atlassian.net/browse/CRIMAP-172
Both domains should work. There is no redirection as this is an API consumed by other services, we want consumers migrating at their own pace to the new URL, and then we can remove the old one.
> CRIMAP-172 Use non-cluster specific domain

- app/services/events/submission.rb
- spec/services/events/submission_spec.rb
Add submitted_at to submission events.
[CRIMRE-184](https://dsdmoj.atlassian.net/browse/CRIMRE-184)
This PR adds submitted_at to the message payload for submission events so that review can use the datastore's submitted_at for calculations and reporting. Without this change, review uses the sns notification timestamp, which could cause discrepancies between the two systems.
[CRIMRE-184]: https://dsdmoj.atlassian.net/browse/CRIMRE-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMRE-184 add submitted_at to submission events

- app/models/crime_application.rb
- lib/tasks/applications.rake
Not to be merged until Apply PR is merged and tested. https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/292
This will reassign all applications in the datastore to an office belonging to the new provider we will be using on Apply staging after integrating with Portal staging.
Previous office code (`1A123B`) belongs to a mock provider, while we used SAMLmock on staging.
The only purpose of this is to keep going as if nothing happened, to not loose all the test applications we already have, needed for testing pagination, and sorting, etc.
To be able to do this more easily making use of active record, temporarily the `application` attribute has been removed from the `attr_readonly` declaration.
After this is merged, and the task is run, a follow-up PR will be raised …
> CRIMAP-38 Task to reassign apps to new office code

- app/models/sorting.rb
- db/migrate/20230321154839_enable_case_insensitive_applicant_name_fields.rb
- db/schema.rb
- spec/api/datastore/v2/searches/search_by_name_and_reference_spec.rb
- spec/api/datastore/v2/searches/sorting_spec.rb
- spec/models/crime_application_spec.rb
- spec/models/sorting_spec.rb
Adds `citext` postgresql module to the `applicant_first_name` and `applicant_last_name` fields to allow case-insensitive ordering
https://dsdmoj.atlassian.net/browse/CRIMRE-162
This seems to be an issue on MacOSX (requires verification on servers) due to the way character set collation is handled by the host operating system Postgres is installed on. ~~The workaround, to add the `lower()` function to the Order By clause may cause performance issues due to the way any indexes based on applicant_first_name/applicant_last_name would be ignored.~~
`citext` postgres module Inspired by https://github.com/ministryofjustice/laa-review-criminal-legal-aid/commit/134adaab21c2a3080e729625fff161d2e0cc72b2
See:
- https://dba.stackexchange.com/questions/106964/why-is-my-postgresql-order-by-case-insensiti …
> [CRIMRE-162] Add Postgresql citext module to applicant name fields

- README.md
- app/api/datastore/base.rb
- app/api/datastore/v2/reviewing.rb
- app/lib/errors.rb
- app/services/operations/mark_as_ready_application.rb
- spec/api/datastore/v2/reviewing/complete_application_spec.rb
- spec/api/datastore/v2/reviewing/mark_as_ready_application_spec.rb
- spec/api/datastore/v2/reviewing/return_application_spec.rb
- spec/rails_helper.rb
- spec/shared_examples/409_error_spec.rb
- Changes the review_state of the application in the Datastore to ready_for_assessment
- Action can only be completed once and an application can only transition from application_received to ready_for_assessment. An error is raised for all other statuses
[CRIMRE-248](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-248)
Me and Tim discussed the investigation to add an index to enforce uniqueness of USN. I have left a comment in the [ticket](https://dsdmoj.atlassian.net/jira/software/c/projects/CRIMRE/boards/960?modal=detail&selectedIssue=CRIMRE-248) explaining how this could be tackled
[CRIMRE-248]: https://dsdmoj.atlassian.net/browse/CRIMRE-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …
> CRIMRE-248 update application review status to ready for assessment

- spec/api/datastore/v2/list_applications_spec.rb
- spec/api/datastore/v2/searches/filter_by_application_id_spec.rb
- spec/api/datastore/v2/searches/filter_by_review_status_spec.rb
- spec/api/datastore/v2/searches/filter_by_status_spec.rb
- spec/api/datastore/v2/searches/search_by_name_and_reference_spec.rb
Update specs to ignore order unless important for the test.
https://github.com/ministryofjustice/laa-criminal-applications-datastore/issues/65
The default sort_by on search is submitted_at. Records for the system specs use insert_all for speed. This means records sometimes have the same submitted_at and therefore the result order becomes inconsistent.
> Fix flickering specs

- app/api/datastore/entities/maat/application.rb
- spec/api/datastore/maat/application_ready_spec.rb
This attribute holds the different IoJ passporting triggered on Apply, and is used on Review to present status badges.
However it is probably not needed for MAAT and we can remove it.
TODO: we may want to do a final audit of attributes once MAAT integration concludes.
> Remove unused `ioj_passport` from MAAT json

- app/models/crime_application.rb
- lib/tasks/applications.rake
Ancillary work required for means passporting refactor.
For context, PRs:
- https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/321
- https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/15
This task will add to all existing applications in the datastore, a new attribute `means_passport`.
Currently all submitted applications are passported `on_benefit_check`, can't be any other value, but soon new submitted applications might also be passported `on_age_under18` so better to run this task soon.
After the task has been run, this PR will be reverted.
https://dsdmoj.atlassian.net/browse/CRIMAP-331
> CRIMAP-331 Task to add `means_passport` attribute

- config/kubernetes/staging/config_map.yml
We are evaluating internal cross-namespace networking between Apply/Review and Datastore.
Internal traffic doesn't use https but Rails by default force it on production environments.
If we decide to keep both, internal cluster connectivity, and external ingress, then we can force the redirect to https at the nginx/ingress level instead of Rails, so both can work (http for internal access and https for external access).
https://dsdmoj.atlassian.net/browse/CRIMAP-328
> CRIMAP-328 Disable rails `force_ssl` setting

- config/routes.rb
- spec/requests/root_spec.rb
This removes a 404 when accessing the datastore root path in production envs, which can be confusing or think the service is down.
> Add empty root path response

- .github/workflows/test-build-deploy.yml
- docker-compose.yml
The version of postgres in cloud platform datastore staging namespace has been upgraded to 15.2.
For consistency, use the same version in the CI/CD pipeline and in the docker-compose file.
[CRIMAP-343](https://dsdmoj.atlassian.net/jira/software/projects/CRIMAP/boards/897?selectedIssue=CRIMAP-343)
[CRIMAP-343]: https://dsdmoj.atlassian.net/browse/CRIMAP-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update postgres ci-cd version following rds upgrade

- Gemfile
- Gemfile.lock
- app/api/datastore/root.rb
- app/api/datastore/v2/applications.rb
- app/api/datastore/v2/reviewing.rb
- app/api/datastore/v2/searches.rb
- spec/api/datastore/root_spec.rb
- spec/api/datastore/v2/create_application_spec.rb
- spec/api/datastore/v2/get_application_spec.rb
- spec/api/datastore/v2/list_applications_spec.rb
- spec/api/datastore/v2/reviewing/complete_application_spec.rb
- spec/api/datastore/v2/reviewing/mark_as_ready_application_spec.rb
- spec/api/datastore/v2/reviewing/return_application_spec.rb
- spec/api/datastore/v2/searches/search_by_name_and_reference_spec.rb
- spec/support/shared_examples/routing_shared_examples.rb
The datastore currently implements authentication via JWT tokens but it doesn’t perform “authorisation“ to limit access of consumers to endpoints that are out of their business.
For instance, we would want MAAT adapter consumer to only have access to the endpoint(s) relevant to them, and to not have access to the create application endpoint, or the search applications endpoint.
In order to do that we have to “annotate“ each endpoint to declare which consumers (JWT issuer) are allowed to call those endpoints. If they are not allowed, return forbidden.
This is making use of the new Grape middleware implemented in the `SimpleJwtAuth` gem that handles this authorisation based on the annotation as a before filter.
NOTE: maat endpoint not yet annotated as it needs a refactor first and agreeing …
> CRIMAP-349 Perform authorisation per endpoint

- app/api/datastore/maat/applications.rb
- config/initializers/simple_jwt_auth.rb
- config/kubernetes/production/deployment.tpl
- config/kubernetes/staging/deployment.tpl
- spec/api/datastore/maat/application_ready_spec.rb
Configure SimpleJwtAuth with the consumer shared secret (created by terraform) for MAAT adapter.
Permit their endpoint.
> Onboard MAAT adapter consumer

- config/initializers/simple_jwt_auth.rb
Instead of `Rails.logger`, use the logger provided by Grape, which will allow us to output to stdout any logging produced by SimpleJwtAuth (in production that will be warns and errors).
The level is still set from Rails logger (different in dev/test and in production).
Wrap the configuration block in a Rails `to_prepare` so the logger is already initialised by the time we are assigning it.
> Change the way SimpleJwtAuth sets the logger

- app/api/datastore/v1/reviewing.rb
- spec/api/datastore/v1/reviewing/return_application_spec.rb
In locking down the different endpoints, I forgot Apply make use of the return endpoint in the developer tools (non-prod) as a quick way to mark an application as returned without having to run Review locally.
This is of great help during development of the IoJ/Means passporting and edge cases as allow for a very quick feedback loop (everything can be done from Apply without Review involvement). Also helpful for quick tests on staging.
For the time being until we don't need this anymore, enable this endpoint again to be called by Apply. Before release, we can turn this off again, or allow it only on non-prod envs (localhost/staging).
> Allow apply to call the return application endpoint

- config/kubernetes/production/prometheus.yml
This is a first bunch of basic prometheus rules that will alert us in the alerts channel whenever they fire.
There is scope to add some more or tweak them so for now I'm adding them here in the code repo, but once we are comfortable with them, we should move this file from the code repo to the infra repo (`cloud-platform-environments`).
https://dsdmoj.atlassian.net/browse/CRIMAP-21
https://dsdmoj.atlassian.net/browse/CRIMRE-225
> CRIMAP-21 Add basic prometheus rules

- config/kubernetes/production/prometheus.yml
Added a new alert for Trivy reported vulnerabilities, and dashboard urls to as many alerts as possible (where available).
https://dsdmoj.atlassian.net/browse/CRIMAP-26
> Add trivy scan prometheus alert and dashboard urls

- config/kubernetes/metabase/ingress.yml
Same as we have with `staging` subdomains. This ensures a more predictable and easy to remember URL.
For now it is a subdomain on apply, as datastore will not have soon public ingress, and review seemed like a less obvious choice.
If in the future we have a separate service for analytics, we can change it easily.
https://dsdmoj.atlassian.net/browse/CRIMAP-372
> Add a subdomain for metabase

- Gemfile
- Gemfile.lock
Use the latest version of the schema gem, which includes enums form several attributes and will not allow the submission of multi class offences.
[CRIMRE-333](https://dsdmoj.atlassian.net/browse/CRIMRE-333)
[CRIMRE-333]: https://dsdmoj.atlassian.net/browse/CRIMRE-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use v0.1.9 of laa schema gem

- Gemfile
- Gemfile.lock
- spec/api/datastore/entities/v1/crime_application_spec.rb
- spec/api/datastore/entities/v1/search_result_spec.rb
- spec/api/datastore/v1/applications/create_application_spec.rb
- spec/models/crime_application_spec.rb
This is part of an overall work to rationalise and remove any unneeded, unused, or superfluous fixtures, as these grow a bit out of hand for a while for no good reason.
On Datastore I've detected a couple superfluous fixtures: application_completed.json and application_invalid.json
These have been replaced by the overarching `application.json`, merging or tweaking the JSON where necessary for the specific test scenario.
https://dsdmoj.atlassian.net/browse/CRIMAP-385
> CRIMAP-385 Remove dependency on unneeded fixtures

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/pruned_application.rb
- app/api/datastore/v1/applications.rb
- spec/api/datastore/v1/applications/create_application_spec.rb
- spec/api/datastore/v1/applications/list_applications_spec.rb
This uses the latest version of the schemas gem (v3.0.0) that supports a new type of schema/struct for a pruned application, reducing drastically the number of attributes returned in the `GET /applications` endpoint.
A new entity has been created to represent this pruned version of the applications, so it is independent of the "main" entity used in other endpoints.
Also, this endpoint is only used on Apply currently, to build the dashboard and paginate through applications, so there should be no impact on any other consumer (Review or MAAT).
https://dsdmoj.atlassian.net/browse/CRIMAP-387
A PR on Apply is also require along with this work, to be deployed together.
> CRIMAP-387 Return list of pruned applications

- app/models/concerns/redactable.rb
- app/models/crime_application.rb
- app/models/redacted_crime_application.rb
- app/services/redacting/base_redacting.rb
- app/services/redacting/redact.rb
- app/services/redacting/rules.rb
- app/services/redacting/unredact.rb
- db/migrate/20230606112337_create_redacted_crime_applications.rb
- db/migrate/20230609142410_add_metadata_to_redacted_table.rb
- db/schema.rb
- spec/models/crime_application_spec.rb
- spec/services/redacting/redact_spec.rb
- spec/services/redacting/rules_spec.rb
- spec/services/redacting/unredact_spec.rb
Please for full context refer to existing open PR #106 as this is an iteration over that one.
This approach is quite similar (in fact I've been able to reuse almost all code with minor to no changes) with the difference the redacted payload (in its entirety, not just the redacted attributes) is stored in a separate table named `redacted_crime_applications`.
The original, unredacted payload, thus reside untouched in the original table `crime_applications`.
The advantage is, as we have it already unredacted, there is no join or any operation on reading back these applications (thus we eliminate N+1 issues). The redacted table can then be used purely for analytics like metabase, by granting access to this table (instead of the "unredacted" one).
Also, no need to make changes to the …
> CRIMAP-402 Redacting PII details v2

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/pruned_application.rb
- spec/api/datastore/v1/applications/list_applications_spec.rb
- spec/api/datastore/v1/maat/applications_spec.rb
Note by merging this PR, many existing submitted applications in the datastore will stop working as their JSON representation will not "fit" into these more strict structs.
However at some point we had to do this, so we will be wiping the staging DB and start fresh, with no baggage.
Another PR will be raised on Apply that will also use this new schemas version, with any required tweaks to the tests.
It is possible Review also needs some tweaks.
https://dsdmoj.atlassian.net/browse/CRIMAP-388
> CRIMAP-388 Bump schemas gem (stricter structs)

- config/kubernetes/staging/psql_job.yml
Follow-up to PR #107.
I've manually dropped the old user and roles so that `metabase` user only has access to the new `redacted_crime_applications` (and `return_details` as before).
We will need to update metabase queries too.
https://dsdmoj.atlassian.net/browse/CRIMAP-402
> Grant permission to metabase user to redacted table

- app/models/crime_application.rb
- app/services/redacting/rules.rb
- config/kubernetes/staging/psql_job.yml
- spec/services/operations/return_application_spec.rb
- spec/services/redacting/redact_spec.rb
- spec/services/redacting/rules_spec.rb
The only bit of information that we need to perform analytics is the return reason. We don't need the free text `details`, and also this may contain PII.
As this is a separate table (`return_details`) we gave access to metabase, but we can remove access with this change.
Another alternative solution would be to refactor the `return_details` table so their attributes are part of the main `crime_application` table (maybe a jsonb or just first level attrs) and remove the table as no longer needed. It holds very little information as it is now. But this involves more work and thinking as it is used in the entities, etc.
More context on slack:
https://mojdt.slack.com/archives/C03JS4V9TPU/p1686748396925349
> Store return reason in the redacted metadata

- config/kubernetes/production/prometheus.yml
Similar changes we did to Apply. Refer to PR
https://github.com/ministryofjustice/laa-apply-for-criminal-legal-aid/pull/390
Note: on Apply error alerts is set to more than 5 errors in 5 mins. Here, given the datastore is a key, central component, better to err on the cautious side, so reducing to 3 errors in 5 mins. We can keep tweaking it depending how it goes.
> Relax some prometheus alerts

- config/kubernetes/metabase/deployment.yml
It seems metabase doesn't play nice whith more than 1 replica. Perhaps requires further investigation but for now is safe to keep it to just 1.
> Keep metabase replicas to just one

- config/kubernetes/metabase/ingress.yml
For some reason modsec was blocking PUT requests. I've also added DELETE as it is probably needed. Basically we want to allow all verb methods as all are required.
Interestingly on Apply/Review this is not an issue (so far) but again we have to keep an eye on modsec logs.
> Set metabase modsec allowed verbs

- config/kubernetes/production/psql_job.yml
Adds a new psql job for the metabase production namespace to have access to the `redacted_crime_applications` table using newly created credentials
[CRIMAP-411](https://dsdmoj.atlassian.net/browse/CRIMAP-411)
[CRIMAP-411]: https://dsdmoj.atlassian.net/browse/CRIMAP-411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Grant metabase prod access to redacted crime applications table

- Gemfile
- Gemfile.lock
Needed because the name of a mandatory attribute on the submission schema has changed.
https://dsdmoj.atlassian.net/browse/CRIMAP-415
> Bump schemas gem to v0.5.0

- .trivyignore
These keep coming back in prometheus alerts and we are unable to fix them as it seems to be on cloud platforms side.
As a test I installed and run Trivy locally (before adding this ignore file that is!) and it didn't detect any vulns so it must have something to do with k8s.
> Ignore trivy vulns outside our control

- config/initializers/filter_parameter_logging.rb
These were coming through when performing searches on Review. `date_of_birth` covers `applicant_date_of_birth`.
Added to the filtering list.
Observe the logs for a search, it should now be:
```
"params":{"search":{"applicant_date_of_birth":"[FILTERED]","application_id_in":"[FILTERED]","application_id_not_in":"[FILTERED]","review_status":["application_received","ready_for_assessment"],"submitted_after":null,"submitted_before":null,"search_text":"[FILTERED]"}
```
> Add some more params to the filter

- Gemfile
- Gemfile.lock
- spec/api/datastore/v1/maat/applications_spec.rb
Bump the schemas gem, which contains the refactor of the appeal attributes, incorporating the new `appeal_lodged_date`.
https://dsdmoj.atlassian.net/browse/CRIMAP-427
> CRIMAP-427 Bump schemas gem (appeal_lodged_date)

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/v1/maat/applications_spec.rb
This PR exposes a `declaration_signed_at` field for MAAT applications for MAAT integration. For the time being, this field returns the `submitted_at` date. It also bumps the schema gem following accompanying schema changes [(#34)](https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/34)
[CRIMRE-387](https://dsdmoj.atlassian.net/browse/CRIMRE-387)
[CRIMRE-387]: https://dsdmoj.atlassian.net/browse/CRIMRE-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Return declaration signed date for maat applications

- app/lib/prometheus_metrics/grape_middleware.rb
- spec/lib/prometheus_metrics/grape_middleware_spec.rb
Currently all API endpoints have controller "other" and action "other", and most of the grafana dashboards work with these controller/action.
To make it more meaningful, the same we had custom labels, we now have default labels for grape API endpoints, where the controller is `(api:method)` (method being get, post, put, etc.) and the action is whatever the endpoint was. This allows for better metrics when using unified Grafana dashboards like golden signals.
Example:
```
ruby_http_requests_total{controller="(api:get)",action="/applications",api_version="v1",api_method="GET",status="200"} 4
ruby_http_requests_total{controller="(api:get)",action="/applications/:application_id",api_version="v1",api_method="GET",status="200"} 1
ruby_http_requests_total{action="ping",controller="status",status= …
```
> Better grafana reports for Grape API endpoints

- app/api/datastore/v1/reviewing.rb
Apply uses this endpoint to trigger application returns from the developer tools footer menu. It is a quick way to test the return journey without needing Review up and running.
However this is not needed in production, and thus this is now env-dependant and the endpoint will not be available to `crime-apply` consumer in production namespace, reducing risk.
This is the only endpoint that requires this differentiation.
https://dsdmoj.atlassian.net/browse/CRIMAP-356
Running `rake grape:routes` with a datastore running with `ENV_NAME=production` will show only `crime-review` as authorised to call the /return endpoint.
> CRIMAP-356 Deauthorise `return` endpoint to apply consumer

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/v1/maat/applications_spec.rb
Necessary changes to go along with the new schemas gem version.
As discussed, the `interests_of_justice` attribute is no longer returned in the MAAT json, and is replaced with a new `ioj_bypass` boolean, whether we captured interests of justice reasons from the provider, or not.
It simplifies business logic for MAAT injection.
Apply / Review services are not affected by this changes and there is no need to bump the schemas gem just for this.
https://dsdmoj.atlassian.net/browse/CRIMAP-436
> CRIMAP-436 Expose `ioj_bypass` in MAAT json

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/base_application_entity.rb
- app/api/datastore/entities/v1/crime_application.rb
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/v1/maat/applications_spec.rb
Counterpart change to go along with change in schemas gem. https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/38
Shifted the `ioj_passport` and `means_passport` attributes to the base entity for clarity but we unexpose  `ioj_passport` in the maat entity.
https://dsdmoj.atlassian.net/browse/CRIMAP-450
> CRIMAP-450 Expose `means_passport` in MAAT json

- config/kubernetes/metabase/deployment.yml
- config/kubernetes/production/psql_job.yml
- config/kubernetes/staging/psql_job.yml
Recommendations based on Snyk, but not all of them are applicable or can work, for instance Metabase will not work if we set the `readOnlyRootFilesystem: true` as it requires write temporary files to the filesystem.
> Add additional container securityContext config

- app/api/datastore/v1/reviewing.rb
Follow-up to previous PR #130.
Further deauthorise `crime-apply` from using the `return` endpoint, in any production environment (this includes any deployed cloud environment, like staging or production).
Only non-prod envs like localhost will be allowed.
More details:
https://mojdt.slack.com/archives/C03JS4V9TPU/p1689342616165039
On staging, trying to return an application from the developer tools, will no longer work.
NOTE: the button will also be removed from Apply in a separate PR later on.
> Deauthorise return endpoint to `apply` consumer

- app/services/redacting/rules.rb
- spec/services/redacting/redact_spec.rb
This is part of a wider investigation Chris Purvis is performing.
So far these 2 need to be unredacted as will be used for reporting purposes. This is information that is required by contract managers.
Clarification on `postcode` is required, but the person in charge of that is on holidays until Monday.
https://dsdmoj.atlassian.net/browse/CRIMAP-464
> CRIMAP-464 Unredact legal rep name attributes

- app/api/datastore/v1/documents.rb
- app/services/operations/documents/delete.rb
- spec/api/datastore/v1/documents/delete_spec.rb
- spec/services/operations/documents/delete_spec.rb
Following up with remaining document operations.
I will raise a counterpart PR on the datastore API gem to be able to call this new endpoint.
I've shared on slack a document on how to test these PRs.
https://dsdmoj.atlassian.net/browse/CRIMAP-525
> CRIMAP-525 Implement delete document endpoint

- app/api/datastore/v1/documents.rb
- app/services/operations/documents/list.rb
- spec/api/datastore/v1/documents/list_spec.rb
- spec/services/operations/documents/list_spec.rb
Following up with remaining document operations.
I will raise a counterpart PR on the datastore API gem to be able to call this new endpoint.
I've shared on slack a document on how to test these PRs.
https://dsdmoj.atlassian.net/browse/CRIMAP-525
It may be we never need this endpoint or to list bucket files directly, in that case this can be deleted later on, but for now it kind of helps with the development and to ensure we have complete API that can be later on reduced/adapted.
> CRIMAP-525 Implement list documents endpoint

- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- docker-compose.yml
fluent bit ingests the logs from stdout in the pods for post processing like kibana etc.
I think some logging was not showing up in the pods due to this not being configured in the config_map.
> Log to stdout in production

- Dockerfile
Add gcombat and to allow ```docker-compose up``` with Apple Silicon
To make sure this does not introduce a regression on Intel Mac, remove any docker files you may already have and run ```docker-compose up```
> Docker compose works with apple silicon

- config/kubernetes/production/config_map.yml
- config/kubernetes/staging/config_map.yml
- docker-compose.yml
This reverts commit 274e3952fff1f6b1bcde31b4508a3e330934555d.
I'm reverting these changes because despite having the expected outcome (Rails.logger.info now shows up), unfortunately in addition to this it also logs every single request (including ping/healthchecks) which is too noisy and has no value at all.
A different approach will be investigated.
> Revert "Log to stdout in production (#146)"

- app/api/datastore/v1/maat/applications.rb
- config/initializers/simple_jwt_auth.rb
- config/kubernetes/staging/deployment.tpl
- spec/api/datastore/v1/maat/applications_spec.rb
New API secrets for MAAT `dev` and `uat` have been injected in their corresponding namespaces and these changes are needed to pick them from the ENV and use them with the JWT authentication.
Their previous solution was to manually hardcode the staging secret so this is an improvement until they move to use a mock sometime in the future.
Slack thread: https://mojdt.slack.com/archives/C04FQ5404KF/p1692010309264049
> Allow MAAT adapter dev and uat to use staging

- Dockerfile
The postgresql-dev and postgresql-client packages used in the Dockerfile were outdated, now that we are running postgres 15.x (locally, CI and also cloud platform through RDS).
This ensure alpine build the image using latest versions of the postgres libraries.
> Update postgresSql clients to fix vulns

- .github/workflows/test-build-deploy.yml
Transition to shortlived secrets for ECR workflow.
See[ here for technical details](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-github-actions)
Relevant cloud platform [PR here](https://github.com/ministryofjustice/cloud-platform-environments/pull/15976)
[CRIMAP-577](https://dsdmoj.atlassian.net/browse/CRIMAP-577)
[CRIMAP-577]: https://dsdmoj.atlassian.net/browse/CRIMAP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use shortlived creds for ECR push

- config/kubernetes/staging/deployment.tpl
Updates staging Kubernetes manifest to set the irsa service account name. More here:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/accessing-aws-apis-and-resources-from-your-namespace.html#using-irsa-in-your-namespace
> Add irsa service account name to staging

- app/services/messaging/events_publisher.rb
- config/kubernetes/production/deployment.tpl
- spec/fixtures/aws/web_identity_token
- spec/services/messaging/events_publisher_spec.rb
- spec/spec_helper.rb
More info here: https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials
Long lived credentials are being immiently removed. Therefore this is a way to test on staging which will give us some assurance of the new approach working in a production like environment. We will then fix forward to add tests, and get the coverage back up.
This PR lowers the min coverage limit to 99% allow merging to test in staging , this will need to be reverted 
Testing for the events publisher has also been commented out and also needs to be updated
> Remove references to long lived credentials sns

- config/kubernetes/staging/deployment.tpl
Removes no longer required long term creds for sanity checking on staging
> Remove sns topic access keys

- app/services/messaging/events_publisher.rb
Remove fallback default strings to ensure `ENV.fetch` fails with an exception
> Remove default env fallbacks

- app/services/operations/documents/traits/s3_operation.rb
- config/kubernetes/staging/deployment.tpl
- spec/services/messaging/events_publisher_spec.rb
- spec/services/operations/documents/delete_spec.rb
- spec/services/operations/documents/list_spec.rb
- spec/services/operations/documents/presign_url_spec.rb
- spec/support/shared_examples/document_operations.rb
- spec/support/shared_examples/stubbed_aws_request.rb
Long lived credentials are being removed from AWS services and datastore staging is currently failing to build due to the deprecated credentials being referenced in the code. Therefore this PR replaces the credentials to pass in the new short lived credentials and updates tests.
[CRIMAP-577](https://dsdmoj.atlassian.net/browse/CRIMAP-577)
[CRIMAP-577]: https://dsdmoj.atlassian.net/browse/CRIMAP-577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Replace deprecated credentials for s3

- app/api/datastore/v1/maat/applications.rb
- spec/api/datastore/v1/maat/applications_spec.rb
Enable MAAT to retrieve data from Review when the application status in Review is 'Complete'.
This is a temporary solution to allow Caseworkers to continue processing in MAAT even if they mark the application as 'Complete' prematurely in Review.
[CRIMAP-574](https://dsdmoj.atlassian.net/browse/CRIMAP-574)
[CRIMAP-574]: https://dsdmoj.atlassian.net/browse/CRIMAP-574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-574 maat api returns completed applications

- .github/workflows/test-build-deploy.yml
This is suppose to fix the problem with incorrectly considering the ECR a secret (and thus not being able to propagate the value to the deploy action) as well as some deprecation warnings.
More info:
https://github.com/aws-actions/configure-aws-credentials#news
> Bump aws action to v3

- app/api/datastore/entities/v1/crime_application.rb
Fixes staging issue where crime applications could not be opened as applications with no supporting evidence were not being handled. Returns an empty array if nil
> Return empty array if no supporting evidence

- app/services/redacting/rules.rb
- spec/services/redacting/redact_spec.rb
- spec/services/redacting/rules_spec.rb
For now we are keeping the collection but with some redacted attributes. We can re-evaluate.
Submit an application with evidence. Open a datastore console and retrieve the submitted application and its redacted record. JSON for evidence should look similar to this:
```
"supporting_evidence"=>
[{"filename"=>"__redacted__", "file_size"=>122796, "content_type"=>"image/png", "s3_object_key"=>"__redacted__"},
{"filename"=>"__redacted__", "file_size"=>128267, "content_type"=>"image/png", "s3_object_key"=>"__redacted__"},
{"filename"=>"__redacted__", "file_size"=>156941, "content_type"=>"image/png", "s3_object_key"=>"__redacted__"}]
```
> Redact supporting evidence

- Gemfile
- Gemfile.lock
- app/api/datastore/base.rb
- app/lib/errors.rb
- app/services/operations/create_application.rb
- spec/api/datastore/entities/v1/crime_application_spec.rb
- spec/api/datastore/v1/applications/create_application_spec.rb
- spec/services/redacting/redact_spec.rb
Update to use same schema version as Apply and Review (which includes "benefit_type")
Return 409 when a duplicate is found on create application
Spec case when submitted application does not include "supporting_evidence"
> Add benefit type

- Gemfile
- Gemfile.lock
- spec/services/redacting/redact_spec.rb
Uses latest Schema gem 1.0.5 to allow default values for document.scan_status
https://dsdmoj.atlassian.net/browse/CRIMAP-675
N/A
> [CRIMAP-675] Update schema gem to 1.0.5

- config/kubernetes/staging/prometheus.yml
Rename trivy prometheus severity label
[CRIMAP-713](https://dsdmoj.atlassian.net/browse/CRIMAP-713)
The label "severity" was causing a collision with CP
[CRIMAP-713]: https://dsdmoj.atlassian.net/browse/CRIMAP-713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAP-713 Rename trivy prometheus severity label

- app/models/crime_application.rb
- spec/models/crime_application_spec.rb
Ensures `first_court_hearing_name` value is always populated, rather than being left as `nil` to ensure data integrity and consistency for consuming services.
https://dsdmoj.atlassian.net/browse/CRIMAP-728
- Should there be a data migration fro any applications in production that still have the `first_court_hearing_name = nil` ?
- Is there a more elegant solution that does not involve callbacks e.g. forcing the consuming service (Apply) to always submit the `first_court_hearing_name` (which would mean a similar behaviour in Apply, and any other service)
- Should `first_court_hearing_name` be allowed to be `nil`?
- The spec iterates a through a 'truth table' of combinations, would a simpler set of context/it blocks be better (but repetitive)?
> [CRIMAP-728] Replicate hearing_court_name into first_court_hearing_name

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- app/models/crime_application.rb
- app/services/utils/work_stream_calculator.rb
- db/migrate/20231106141454_add_work_stream_to_crime_applications.rb
- db/schema.rb
- spec/api/datastore/entities/v1/crime_application_spec.rb
- spec/services/utils/work_stream_calculator_spec.rb
Adds an a work stream field to the `crime_application` table which is indexed to enable searching on review. When an application is created, the appropriate work steam is calculated and saved. The field is also omitted from maat applications.
[CRIMAP-726](https://dsdmoj.atlassian.net/browse/CRIMAP-726)
[CRIMAP-726]: https://dsdmoj.atlassian.net/browse/CRIMAP-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAP-726] Calculate work stream of application at point of submission

- config/kubernetes/production/deployment.tpl
Adds S3 bucket to production deployment, based on cloud-platform https://github.com/ministryofjustice/cloud-platform-environments/pull/17713
https://dsdmoj.atlassian.net/browse/CRIMAPP-66
Test evidence upload via production
> [CRIMAP-66] Add S3 to production

- Gemfile
- Gemfile.lock
- db/schema.rb
Schema change to allow `lost_job_in_custody` data
Updates DB schema to include missing default value and index for `work_stream`
https://dsdmoj.atlassian.net/browse/CRIMAPP-129
Note change to Schema: Index and default value for work_streams was missing in schema even though specified in migration
> [CRIMAP-129] Upgrade DB Schema for lost_job_in_custody and schema change

- app/api/datastore/entities/v1/search_result.rb
- app/api/datastore/v1/searching.rb
- app/models/search_filter.rb
- app/models/sorting.rb
- db/migrate/20231117142406_add_return_reason_virtual_attribute_to_crime_applications.rb
- db/migrate/20231117142441_add_index_for_office_code_virtual_attribute_on_crime_applications.rb
- db/schema.rb
- spec/api/datastore/entities/v1/search_result_spec.rb
- spec/api/datastore/v1/searching/filter_by_reviewed_at_spec.rb
Add office_code, provider_name, return_reason, and return details to search results.
Add reviewed_at filters
Allow sorting of search results by return_reason, office_code, and reference.
[CRIMAPP-89](https://dsdmoj.atlassian.net/browse/CRIMAPP-89)
Required by https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/465
[CRIMAPP-89]: https://dsdmoj.atlassian.net/browse/CRIMAPP-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  CRIMAPP-89 add search filters and attributes for return reasons report

- Gemfile
- Gemfile.lock
Update Schema to use the latest work stream names.
[CRIMAPP-254](https://dsdmoj.atlassian.net/browse/CRIMAPP-254)
[CRIMAPP-253](https://dsdmoj.atlassian.net/browse/CRIMAPP-253)
Updates to use the following version of the schema:
https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/commit/18cd5b3f6c461178be1190ed18b4e0e50cc04f7a
Required by this Review PR https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/481
[CRIMAPP-254]: https://dsdmoj.atlassian.net/browse/CRIMAPP-254?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-253]: https://dsdmoj.atlassian.net/browse/CRIMAPP-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Use latest work stream name names

- app/api/datastore/entities/v1/search_result.rb
- app/api/datastore/v1/searching.rb
- app/models/search_filter.rb
- app/models/sorting.rb
- db/migrate/20231218161740_add_case_type_virtual_attribute_to_crime_applications.rb
- db/schema.rb
- spec/api/datastore/entities/v1/search_result_spec.rb
- spec/api/datastore/v1/searching/filter_by_case_type_spec.rb
Adds application type and case type to search results. Also adds case_type as a virtual attribute to facilitate sorting by case type in the search table in review
[CRIMAPP-282](https://dsdmoj.atlassian.net/browse/CRIMAPP-282)
Requires pulling down the review changes to test: https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/492
Instructions for testing in the review PR
[CRIMAPP-282]: https://dsdmoj.atlassian.net/browse/CRIMAPP-282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-282] Add case and application type to search results

- app/api/datastore/entities/v1/search_result.rb
- spec/api/datastore/entities/v1/search_result_spec.rb
Expose means_passport to allow Review to display in return reasons means column the means test as opposed to hard-coding 'passported
https://dsdmoj.atlassian.net/browse/CRIMAPP-364
> Expose means passport on search results

- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/v1/maat/applications_spec.rb
A recent refactor had caused overall_offence class attribute not to be added to the case_details. This PR fixes that and fixes the spec to make sure it cannot happen again.
Test on staging. Confirm application has an overall offence class on Review. Add to MAAT and confirm the offence class is copied over.
> Make sure overall offence class is passed to MAAT

- app/services/redacting/redact.rb
- app/services/redacting/rules.rb
- spec/services/redacting/redact_spec.rb
- spec/services/redacting/rules_spec.rb
Redacts `additional_information` text ahead of feature release
[CRIMAPP-449](https://dsdmoj.atlassian.net/browse/CRIMAPP-449)
Submit an application with additional information. Open a datastore console and retrieve the submitted application and its redacted record. JSON for additional information should look similar to this:
```
"additional_information"=>"__redacted__"
``` 
[CRIMAPP-449]: https://dsdmoj.atlassian.net/browse/CRIMAPP-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-449] Redact additional information

- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
- spec/api/datastore/v1/applications/get_application_spec.rb
- spec/api/datastore/v1/maat/applications_spec.rb
A few superfluous attributes were added unnecessarily to the MAAT application JSON. This PR does the following:
1. Adds a spec to ensure that only attributes defined in the `maat_application` schema are present in the entity.
2. Adjusts extra details from the `crime_application` to be opt-in rather than opt-out, ensuring that adding new attributes to the entity is a deliberate choice.
In this process, the following attributes have been removed from the MAAT application:
From root:
- `reviewed_at`
From `case_details`:
- `date_case_concluded`
- `date_client_remanded`
- `has_case_concluded`
- `is_client_remanded`
- `is_preorder_work_claimed`
- `preorder_work_date`
- `preorder_work_details`
Deploy to staging and confirm that MAAT integration works okay.
> Ensure maat application only inlcude attributes in the schema

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
Adds basic means details to the MAAT API
This PR is contingent on https://github.com/ministryofjustice/laa-criminal-legal-aid-schemas/pull/93 
If you want to test it before the merge then you can set schemas to the latest commit for PR 93 above like so:
```ruby
gem 'laa-criminal-legal-aid-schemas',
github: 'ministryofjustice/laa-criminal-legal-aid-schemas', ref: '92580fc4f29ea7fa3c4e27769e0fc1f87f271a07'
```
Probably best to get the schema merged first and then test this.
Steps to test locally
1. comment out the following lines in `app/api/datastore/root.rb`
```ruby
auth :jwt
use SimpleJwtAuth::Middleware::Grape::Authorisation
```
this will allow you to do a GET as if you were MAAT without worrying about auth.
2. Set all the feature flags to production mode, and do a regression where you …
> Crimapp 453 change maat schema unemployed journey

- Gemfile
- Gemfile.lock
Allow Outgoings Payments to be submitted/rehydrated 
https://dsdmoj.atlassian.net/browse/CRIMAPP-218
> [CRIMAPP-218] Bump schema v1.0.40

- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
MAAT doesn't want to handle 'none' and nil for benefit_type, as they amount to the same thing. We don't want to store it as nil for us, as there is a difference to Apply and Review between the two values. This therefore was the best place to transform it.
https://dsdmoj.atlassian.net/browse/CRIMAPP-604
> Replace benefit_type none with nil for MAAT

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
Add splat to extract strings from arrays
Updates key names for income_benefits and income_payments
Crime Core devs requested that details were pulled out of metadata as the nesting caused trouble with the way their mappings build models and they only need details and nothing else
Looks like rubocop removed this splat after we'd tested it last time, so MAAT endpoint lost access to these exposed values. 
Keys and values have changed over time and have broken tests that match schema with fixtures
Steps to test locally
1. comment out the following lines in app/api/datastore/root.rb
`auth :jwt`
`use SimpleJwtAuth::Middleware::Grape::Authorisation`
this will allow you to do a GET as if you were MAAT without worrying about auth.
2. Set all the feature flags to production mode, and do a …
> Add splat to extract strings from arrays

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
Fix exposing means to MAAT endpoint
Add splat to extract strings from arrays
Updates key names for income_benefits and income_payments
Crime Core devs requested that details were pulled out of metadata as the nesting caused trouble with the way their mappings build models and they only need details and nothing else
Add null safety checks to allow for applications with no means details to still be fetched correctly. 
Looks like rubocop removed this splat after we'd tested it last time, so MAAT endpoint lost access to these exposed values. 
Keys and values have changed over time and have broken tests that match schema with fixtures
Steps to test locally
1. comment out the following lines in app/api/datastore/root.rb
`auth :jwt`
`use SimpleJwtAuth::Middleware::Grape::Authorisation`
this will …
> Fix exposing means to MAAT endpoint

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/application.rb
Expose capital details for MAAT
https://dsdmoj.atlassian.net/browse/CRIMAPP-618
1. comment out the following lines in app/api/datastore/root.rb
```
auth :jwt
use SimpleJwtAuth::Middleware::Grape::Authorisation
```
this will allow you to do a GET as if you were MAAT without worrying about auth.
2. Set all the feature flags to production mode, and do a regression where you submit and application, send it back, re-submit, and Mark it as ready for MAAT
3. Turn on the means assessment features, and submit an application with means info, send it back, re-submit and then mark it ready for MAAT
4. With postman or just your browser make a GET request to /api/v1/maat/applications/:usn where the USN is either the non-means case or the case with means info.
5. You should then see the JSON response - …
> [CRIMAPP-618] Expose capital details for MAAT

- Gemfile
- Gemfile.lock
- app/lib/types.rb
NOTE: Schema structs now support in-progress applications. The datastore does not include these, so the schema type `Types::ApplicationStatus` is overridden to exclude in-progress applications.
> Update to schema 1.1.3

- app/api/datastore/entities/v1/maat/application.rb
- Removed "employment_details"
- Added "employment_income_payments"
https://dsdmoj.atlassian.net/browse/CRIMAPP-1140
> CRIMAPP-1140 : Apply - Maat intergration: Employed Income amount not being injected

- app/services/utils/work_stream_calculator.rb
- spec/services/utils/work_stream_calculator_spec.rb
Refactors work stream calculator to calculate non means queue with the `is_means_tested` attribute rather than the means passport value. This is to prevent inaccuracies in the event that an application is resubmitted and the means passport value has not been updated
[CRIMAPP-1195](https://dsdmoj.atlassian.net/browse/CRIMAPP-1195)
Follow steps in ticket
[CRIMAPP-1195]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1195] Calculate non means queue with `is_means_tested` attribute

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/income_details.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
Expose 'income_details' attributes to MAAT
- manage_without_income
- manage_other_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-963
> CRIMAPP-963: Expose 'How does your client manage with no income?' attributes to MAAT

- app/api/datastore/entities/v1/maat/capital_details.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
Expose 'capital_details' attributes to MAAT
- partner_trust_fund_amount_held
https://dsdmoj.atlassian.net/browse/CRIMAPP-1117
> [!NOTE]  
> We will be sending both attributes 'trust_fund_amount_held' and 'partner_trust_fund_amount_held'. MAAT will sum it up and display in the relevant column
> CRIMAPP-1117 - MAAT integration - 'partner_trust_fund' does not inject into MAAT

- app/services/utils/work_stream_calculator.rb
- spec/services/utils/work_stream_calculator_spec.rb
Applications will now be referred to the criminal applications team 2 queue if there is a:
- a restraint or freezing order
- a rental income payment
https://dsdmoj.atlassian.net/browse/CRIMAPP-1246
https://dsdmoj.atlassian.net/browse/CRIMAPP-1247
Pull down this branch and submit the following applications on apply:
- An application with a restraint or freezing order answered in the income section
- An application with a restraint or freezing order answered in the capital section
- An application with an income payment with the payment type 'rent'
These applications should appear in the cat2 queue in review
> [CRIMAPP-1246, CRIMAPP-1247] Update cat2 stream calculation logic

- app/api/datastore/entities/v1/maat/income_details.rb
- app/services/utils/maat/other_income_base.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
- Avoid updating original objects(`income_payments` and `income_benefits`) when passed to `Utils::MAAT::OtherIncomePaymentCalculator` because annualised amount will be updated always by number of times `.call` is invoked
- Instead, create a copy of `income_payments` and `income_benefits` and pass as a parameter to  `Utils::MAAT::OtherIncomePaymentCalculator` 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1119
> Crimapp-1119 Fix annualisation

- app/services/status/healthcheck.rb
- config/kubernetes/staging/deployment.tpl
For testing on staging:
- use ping for Liveness probe
- user start probe
- user simple query for healthcheck
[CRIMAPP-345](https://dsdmoj.atlassian.net/browse/CRIMAPP-345)
The liveness probe was previously using the same endpoint as the readiness probe, which included a database connection check. We suspect that when the liveness probe takes too long due to database latency, it triggers unnecessary container restarts.
This update removes the database check from the liveness probe and also removes liveness initial delay, which should prevent restarts caused by temporary database connection issues.
[CRIMAPP-345]: https://dsdmoj.atlassian.net/browse/CRIMAPP-345?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-345 fix pod crash loop

- Gemfile
- Gemfile.lock
- app/services/utils/work_stream_calculator.rb
- spec/services/utils/work_stream_calculator_spec.rb
Applications where the client and/or partner is in the armed forces are routed to CAT2.
[CRIMAPP-1300](https://dsdmoj.atlassian.net/browse/CRIMAPP-1300)
[CRIMAPP-1300]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1300] Route armed forces to CAT2

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/capital_details.rb
- app/api/datastore/entities/v1/maat/income_details.rb
- app/api/datastore/entities/v1/maat/means_details.rb
- app/services/utils/maat/other_income_payment_calculator.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
- spec/services/redacting/redact_spec.rb
- Expose `trust_fund_yearly_dividend` and `partner_trust_fund_yearly_dividend` attributes to MAAT API
- Trust fund dividend attributes (`trust_fund_yearly_dividend`, `partner_trust_fund_yearly_dividend`) belongs to `capital_details` object. To add trust funds to 'other_incomes' we need to pass these attributes to `income_details` object.
- Create additional attribute `dividends` to hold `trust_fund_yearly_dividend` and  `partner_trust_fund_yearly_dividend`
- Merge `dividends` with `income_details` object to calculate and add to total value of 'Other Income' in MAAT
https://dsdmoj.atlassian.net/browse/CRIMAPP-1318
> [!NOTE]   
> Specs are failing because of old schema version
> [!IMPORTANT]  
> TODO: Update schema version after approval: …
> CRIMAPP-1318  Dividends from a trust fund - considered as ‘income’ and needs to be added to the total value of 'Other Income' in MAAT

- Gemfile
- Gemfile.lock
- app/api/datastore/entities/v1/maat/case_details.rb
- spec/api/datastore/entities/v1/maat/application_spec.rb
- Validation error occurs when correspondence_address_type is not present. So we need to make it optional as   `correspondence_address_type` is not required for 'Appeal to crown court' applications
- Exposing  :appeal_usn attribute (may be required for MAAT)
https://dsdmoj.atlassian.net/browse/CRIMAPP-1288
https://ministryofjustice.sentry.io/issues/5635408008/?environment=staging&project=4507142468468736&referrer=project-issue-stream&statsPeriod=1h
> [!IMPORTANT]  
> TODO: Update schema version once approved
> CRIMAPP-1288 Appeal to crown court applications not injecting to MAAT

- Gemfile
- Gemfile.lock
- spec/api/datastore/entities/v1/maat/application_spec.rb
Validation error occurs when `#/case_details/hearing_date` is not present. So we need to make it optional as **hearing_date** is not required for **A change in financial circumstances** > **Appeal to crown court applications**
https://dsdmoj.atlassian.net/browse/CRIMAPP-1288
Staging Application: 10002637
> CRIMAPP-1288 Appeal to crown court applications not injecting to maat with missing hearing date

- Gemfile
- Gemfile.lock
Bump laa-criminal-legal-aid-schemas to v1.3.3
[CRIMAPP-825](https://dsdmoj.atlassian.net/browse/CRIMAPP-825)
[CRIMAPP-825]: https://dsdmoj.atlassian.net/browse/CRIMAPP-825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Bump laa-criminal-legal-aid-schemas to v1.3.3

- app/services/events/submission.rb
- spec/services/events/submission_spec.rb
Adds reference( aka 'usn') to the sns message body.
The submission history event stream is based on the reference (usn). Adding reference to this event, allows them to be linked without an additional request to the data store or loading the review aggregate.
(see also: https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/708 for CrimeReview changes)
> [CRIMAPP-1333] Add reference to submission event data

- Gemfile
- Gemfile.lock
- app/api/datastore/v1/reviewing.rb
- app/services/operations/complete_application.rb
- db/migrate/20241101173540_add_case_id_to_decisions.rb
- db/schema.rb
- spec/api/datastore/v1/reviewing/complete_application_spec.rb
1. Added the missing decision attributes to the `complete` endpoint params.
2. Added `case_id` to `decisions`.
3. Added decision validation to the `CompleteApplication` service.
[CRIMAPP-1398](https://dsdmoj.atlassian.net/browse/CRIMAPP-1398)
[CRIMAPP-1398]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1398] Add missing decision attributes

- .github/workflows/test-build-deploy.yml
Updated the following GitHub Actions dependencies:
1. `actions/checkout@v3` -> `actions/checkout@v4`
2. `actions/upload-artifact@v3` - > `actions/upload-artifact@v4`
3. `aws-actions/configure-aws-credentials@v3` - > `aws-actions/configure-aws-credentials@v4`
4. `aws-actions/amazon-ecr-login@v1` - > `aws-actions/amazon-ecr-login@v2`
[CRIMAPP-1353](https://dsdmoj.atlassian.net/browse/CRIMAPP-1353)
[CRIMAPP-1353]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update GitHub Actions

- app/services/redacting/metadata_wrapper.rb
- spec/services/operations/return_application_spec.rb
- spec/services/redacting/redact_spec.rb
Adds attributes to metadata json to fix filtering issue in metabase 
Metabase restricts the number of filter fields for nested json, see warning message:
`WARN metabase.driver.sql-jdbc.sync.describe-table More nested field columns detected than maximum. Limiting the number of nested field columns to 100.`
The `submitted_application` json has exceeded this limit. This meant fields that were previously available to use on metabase to create new reports or filter existing reports were missing or no longer working
As the metadata json is under the limit of 100, making filters of interested available on the metadata should make it possible to filter on those attributes added 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1513
> [CRIMAPP-1513] Metabase metadata update

- Gemfile
- Gemfile.lock
Allow decisions without court_type
[CRIMAPP-1590](https://dsdmoj.atlassian.net/browse/CRIMAPP-1590)
[CRIMAPP-1590]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CRIMAPP-1590 Allow decisions without a court type

- config/kubernetes/metabase/deployment.yml
Update to the Metabase deployment file to target the new secrets generated by AWS Secrets Manager.
[CRIMAPP-1523](https://dsdmoj.atlassian.net/browse/CRIMAPP-1523)
[CRIMAPP-1523]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1523] Target AWS secrets on metabase

- config/localstack/ready.sh
- docker-compose.yml
Accompanying Review PR: https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/905
This change adds SQS to LocalStack and subscribes a queue to SNS so that the new SQS <--> SNS messaging system can be replicated locally.
[CRIMAPP-1821](https://dsdmoj.atlassian.net/browse/CRIMAPP-1821)
[CRIMAPP-1821]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1821] Add SQS to LocalStack

- db/migrate/20251002105112_add_soft_deleted_at_to_crime_applications.rb
- db/schema.rb
- deleting/lib/deleting.rb
- deleting/lib/deleting/commands/delete.rb
- deleting/lib/deleting/deletable.rb
- deleting/lib/deleting/handlers/update_application_soft_deleted.rb
- spec/deleting/automate_deletion_returned_application_spec.rb
- add `soft_deleted_at` to `crime_applications`
- link `UpdateApplicationSoftDeleted` listener to `SoftDeleted` event to update the application's `soft_deleted_at` timestamp
- add `state` to `Deletable` aggregate
[CRIMAPP-1945](https://dsdmoj.atlassian.net/browse/CRIMAPP-1945)
[CRIMAPP-1945]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CRIMAPP-1945] Add soft_deleted_at
