app/api/datastore/base.rb, app/api/datastore/v2/applications.rb, spec/api/datastore/v2/applications_spec.rb
Adds V2 endpoint for retrieving applications.
[CRIMAP-219](https://dsdmoj.atlassian.net/browse/CRIMAP-219)
I have not created a service for the get operation. Happy to create one for this operation if people think it worthwhile.
=> Crimap 219 v2 get application

.rubocop.yml, app/api/datastore/base.rb, app/api/datastore/entities/search_result.rb, app/api/datastore/root.rb, app/api/datastore/v2/applications.rb, app/api/datastore/v2/searches.rb, app/models/pagination.rb, app/models/search_filter.rb, app/services/operations/search.rb, spec/api/datastore/v2/searches/filter_by_application_id_spec.rb
Add search endpoint and allow filtering by application_id.
This feature is part of the initial spike of the search endpoint for Review.
[CRIMRE-44](https://dsdmoj.atlassian.net/browse/CRIMRE-44)
Filtering by application_id will be used on review to scope searched applications to those of a given caseworker.
=> CRIMRE-83 Search by application id.

Gemfile.lock, app/services/operations/list_applications.rb, db/migrate/20230111165520_add_completed_at_to_crime_applications.rb, db/schema.rb, spec/api/datastore/v2/list_applications_spec.rb
Add support for completed status. 
updates to latest schema gem
adds completed_at timestamp
updates specs for filtering by completed status
=> Update LaaSchamas gem to include compelted status

Gemfile.lock, app/api/datastore/entities/search_result.rb, app/api/datastore/v2/searches.rb, app/lib/types.rb, app/models/search_filter.rb, app/services/operations/list_applications.rb, db/migrate/20230112140053_add_review_status_review_reason_and_timestamps_to_crime_applications.rb, db/schema.rb, spec/api/datastore/v2/list_applications_spec.rb, spec/api/datastore/v2/searches/filter_by_review_status_spec.rb, spec/api/datastore/v2/searches/filter_by_submitted_at_spec.rb
Add review status to search filter + remove "completed" status
CRIMRE-52
=> Crimre 52 store review status separately

.rubocop.yml, app/api/datastore/base.rb, app/api/datastore/helpers/pagination_params.rb, app/api/datastore/helpers/sorting_params.rb, app/api/datastore/v2/applications.rb, app/models/sorting.rb, app/services/operations/list_applications.rb, spec/api/datastore/v2/list_applications_spec.rb
Some due refactor of the sorting. Made it behave similar to the existing Pagination so it can use `apply_to_scope`.
It now support passing an `order` to choose the column to sort by (previously we were always hardcoding this to either submitted_at or returned_at). Fixes a bug on Apply dashboard.
Reorganised the helpers.
Ensure the tests are exercising the different sort columns and directions.
Made it `asc` and `ascending`, and `desc` and `descending` aliases.
NOTE 1: there are no functional changes, everything will keep working as it is (no changes needed on Apply and I suspect none on Review either). Same query params on the outside.
NOTE 2: I'm not really happy with the naming of the query params for sorting. They seem confusing to me. Currently we are using `order` for the column to …
=> Refactor list applications sorting and pagination

app/api/datastore/v2/reviewing.rb, app/models/return_details.rb, app/services/operations/return_application.rb, db/migrate/20230124120841_rename_return_details_reason_type_reason.rb, db/schema.rb, spec/api/datastore/v2/reviewing/return_application_spec.rb, spec/services/operations/return_application_spec.rb
Renames ReturnDetails#reason_type ReturnDetails#reason
Part of CRIMRE-52
=> CRIMRE-52 rename reason_type reason

Gemfile.lock, README.md, app/api/datastore/base.rb, app/api/datastore/v2/reviewing.rb, app/lib/errors.rb, app/models/crime_application.rb, app/services/operations/complete_application.rb, app/services/operations/return_application.rb, spec/api/datastore/v2/list_applications_spec.rb, spec/api/datastore/v2/reviewing/complete_application_spec.rb, spec/api/datastore/v2/reviewing/return_application_spec.rb, spec/api/datastore/v2/searches/filter_by_status_spec.rb
Adds an operation to mark an application as complete via a new {id}/complete endpoint
Updates review_status
https://dsdmoj.atlassian.net/browse/CRIMRE-148
=> Add close application operation

app/services/utils/offence_class_calculator.rb, spec/models/crime_application_spec.rb, spec/services/utils/offence_class_calculator_spec.rb
Overall offence class was not being calculated as the calculator was expecting symbolised keys. This has been corrected
=> Fix offence class calculation

app/api/datastore/entities/v1/crime_application.rb, spec/api/datastore/entities/v1/crime_application_spec.rb
Include parent_id in crime_application entity
[CRIMRE-322](https://dsdmoj.atlassian.net/browse/CRIMRE-322)
[CRIMRE-322]: https://dsdmoj.atlassian.net/browse/CRIMRE-322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMRE-322 include parent_id in crime_application entity

app/services/redacting/rules.rb, spec/services/redacting/redact_spec.rb, spec/services/redacting/rules_spec.rb
This may contain PII and is not needed for anything useful on metabase. The IoJ types are the important thing to keep.
=> Redact IoJ reasons free text

config/kubernetes/metabase/ingress.yml
We have to keep an eye on the logs as there might be a risk of genuine requests being blocked.
=> Enable modsec on metabase ingress

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/base_application_entity.rb, spec/services/redacting/redact_spec.rb
Cleaned up unneeded code once we start using schemas gem v1.0.0
https://dsdmoj.atlassian.net/browse/CRIMAP-442
=> Bump schemas gem to v1.0.0

.github/workflows/test-build-deploy.yml
=> Adds github sha tagged image without suffix

config/kubernetes/production/deployment.tpl
Remove missed references to access key and ids in prod tpl file
https://dsdmoj.atlassian.net/browse/CRIMAP-577
=> [CRIMAP-577] Remove references to access key and ids

Gemfile, Gemfile.lock
https://ministryofjustice.sentry.io/alerts/rules/details/143747/?alert=7266&environment=production&notification_uuid=cd926de7-e22d-4c5f-aff7-c95d737d5054&referrer=metric_alert_slack
=> HOTFIX update schema

Gemfile, Gemfile.lock
=> Bump schema to v1.0.18

Gemfile, Gemfile.lock
=> Bump schema to v1.0.20

Gemfile, Gemfile.lock
Upgrade Schema to allow throughput of `outgoings_details`
https://dsdmoj.atlassian.net/browse/CRIMAPP-224
N/A
=> [CRIMAP-224] Upgrade schema v1.0.22 (outgoings)

app/models/pagination.rb, db/schema.rb, spec/api/datastore/v1/applications/list_applications_spec.rb
Increase search limit for csv reports
Correct schema entry for work_stream
[CRIMAPP-87](https://dsdmoj.atlassian.net/browse/CRIMAPP-87)
required by: https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/504
[CRIMAPP-87]: https://dsdmoj.atlassian.net/browse/CRIMAPP-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Increase search limit for reporting

Gemfile, Gemfile.lock, config/initializers/sentry.rb
Adds profilling and performance monitoring for sentry
See:
https://docs.sentry.io/product/performance
https://docs.sentry.io/product/profiling
=> Enable sentry profiling and performance monitoring

Gemfile.lock
=> Upgrade to puma 6.4.3

Dockerfile
Upgrade Alpine from 3.18 --> 3.19
=> Upgrade Alpine to 3.19

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/base_application_entity.rb, app/api/datastore/entities/v1/crime_application.rb, app/api/datastore/entities/v1/maat/application.rb, app/api/datastore/entities/v1/post_submission_evidence_application.rb, app/api/datastore/entities/v1/pruned_application.rb, spec/api/datastore/v1/applications/get_application_spec.rb, spec/api/datastore/v1/maat/applications_spec.rb
Update to use latest schema in support of PSE
Include `additional_information` 
Refactor to move methods to the entity base class.
[CRIMAPP-362](https://dsdmoj.atlassian.net/browse/CRIMAPP-362)
[CRIMAPP-362]: https://dsdmoj.atlassian.net/browse/CRIMAPP-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Crimapp 362 support additional information

config/initializers/sentry.rb
responding to this re this request: https://mojdt.slack.com/archives/C02AFLHGK9S/p1706098331923819
=> Change sentry sampling rate

Gemfile, Gemfile.lock
Update schema to support a PSE applicant.
[CRIMAPP-419](https://dsdmoj.atlassian.net/browse/CRIMAPP-419)
PSE only cares about name and DOB, for example.
[CRIMAPP-419]: https://dsdmoj.atlassian.net/browse/CRIMAPP-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Support PSE applicant

app/api/datastore/v1/searching.rb, app/models/search_filter.rb, db/migrate/20240126131332_add_application_type_virtual_attribute_to_crime_applications.rb, db/schema.rb, spec/api/datastore/v1/searching/filter_by_application_type_spec.rb
Add application type to search filter
[CRIMAPP-421](https://dsdmoj.atlassian.net/browse/CRIMAPP-421)
[CRIMAPP-421]: https://dsdmoj.atlassian.net/browse/CRIMAPP-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-421] Add application type to search filter

Gemfile, Gemfile.lock, spec/api/datastore/v1/maat/applications_spec.rb
Add attributes
- is_preorder_work_claimed
- preorder_work_date
- preorder_work_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-368
=> CRIMAPP-368 Add pre-order-work attributes support

Gemfile, Gemfile.lock
Allows Income Payments/Benefits rehydration/submission
https://dsdmoj.atlassian.net/browse/CRIMAPP-114
https://dsdmoj.atlassian.net/browse/CRIMAPP-117
https://dsdmoj.atlassian.net/browse/CRIMAPP-214
N/A
=> [CRIMAPP-117] Bump schema to v1.0.39

Gemfile, Gemfile.lock
Bump Schema v1.0.46 which includes outgoings updates
https://dsdmoj.atlassian.net/browse/CRIMAPP-497
N/A
=> [CRIMAPP-497] Bump Schema v1.0.46

Gemfile, Gemfile.lock
Bump schema version to v1.0.50
=> Increment schema version

Gemfile, Gemfile.lock
Following update of fixture file
=> Update schema version

Gemfile, Gemfile.lock
Changes include adding new attribute to capital and type and fixture updates.
[CRIMAPP-505](https://dsdmoj.atlassian.net/browse/CRIMAPP-505)
[CRIMAPP-505]: https://dsdmoj.atlassian.net/browse/CRIMAPP-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update schema to v1.0.54

app/models/sorting.rb
Sort by application_type
[CRIMAPP-348](https://dsdmoj.atlassian.net/browse/CRIMAPP-348)
Confirm that sorting of open applications is possible using this PR and https://github.com/ministryofjustice/laa-review-criminal-legal-aid/pull/560
[CRIMAPP-348]: https://dsdmoj.atlassian.net/browse/CRIMAPP-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-348 sort by application type

Gemfile, Gemfile.lock
=> Update schema version to v1.0.56

Gemfile, Gemfile.lock
Add capitals.has_no_other_assets to capital_details
https://dsdmoj.atlassian.net/browse/CRIMAPP-506
=> Update schema to v1.0.57

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, spec/api/datastore/entities/v1/maat/application_spec.rb
Reverts ministryofjustice/laa-criminal-applications-datastore#233
=> Revert "Add splat to extract strings from arrays"

Gemfile, Gemfile.lock
=> Upgrade schema version to v1.0.59

.gitignore, Gemfile, Gemfile.lock
=> Update schema version to v1.0.63

Gemfile, Gemfile.lock, spec/services/redacting/redact_spec.rb
=> Bump schema to 1.0.66

Gemfile, Gemfile.lock
=> [CRIMAPP-735] Bump schema version

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, spec/services/redacting/redact_spec.rb
Update schema to v1.0.71
[CRIMAPP-776](https://dsdmoj.atlassian.net/browse/CRIMAPP-776)
[CRIMAPP-776]: https://dsdmoj.atlassian.net/browse/CRIMAPP-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-776] Update schema to v1.0.71

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, spec/services/redacting/redact_spec.rb
[CRIMAPP-776](https://dsdmoj.atlassian.net/browse/CRIMAPP-776)
[CRIMAPP-776]: https://dsdmoj.atlassian.net/browse/CRIMAPP-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-776] Update schema and attribute name

config/kubernetes/staging/deployment.tpl
Remove entry for staging maat_adapter
[LAA-REVIEW-CRIMINAL-LEGAL-AID-B](https://ministryofjustice.sentry.io/issues/5342998996/)
=> Remove redundant MAAT staging adapter

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, spec/api/datastore/entities/v1/maat/application_spec.rb, spec/services/redacting/redact_spec.rb
Updates schema version + fixes failing specs
[CRIMAPP-840](https://dsdmoj.atlassian.net/browse/CRIMAPP-840)
[CRIMAPP-840]: https://dsdmoj.atlassian.net/browse/CRIMAPP-840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-840] Update schema to v1.1.1

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, spec/services/redacting/redact_spec.rb
Bumps schema version based on CRIMAPP-912 updates
[CRIMAPP-912](https://dsdmoj.atlassian.net/browse/CRIMAPP-912)
[CRIMAPP-912]: https://dsdmoj.atlassian.net/browse/CRIMAPP-912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-912] Update schema version 

Gemfile, Gemfile.lock
Update to to schema v1.1.7
[CRIMAPP-945](https://dsdmoj.atlassian.net/browse/CRIMAPP-945)
[CRIMAPP-945]: https://dsdmoj.atlassian.net/browse/CRIMAPP-945?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update schema to v1.1.7

Gemfile, Gemfile.lock
=> Update schema version to v1.1.10

Gemfile, Gemfile.lock
Bump schema version to v1.1.12
https://dsdmoj.atlassian.net/browse/CRIMAPP-875
=> Update schema version to v1.1.12

Gemfile, Gemfile.lock
=> Upgrade schema version to v1.1.13

Gemfile, Gemfile.lock
=> Upgrade schema to v1.1.14

Gemfile, Gemfile.lock
[CRIMAPP-992](https://dsdmoj.atlassian.net/browse/CRIMAPP-992)
[CRIMAPP-992]: https://dsdmoj.atlassian.net/browse/CRIMAPP-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update schema to v1.1.15

Gemfile, Gemfile.lock
=> Upgrade schema to v1.1.19

Gemfile, Gemfile.lock
=> Update schema version to v1.1.20

Gemfile, Gemfile.lock, spec/services/redacting/redact_spec.rb
=> Update schema version to v1.1.22 and fix 'redact_spec'

Dockerfile
Use up-to-date AWS CA bundle for RDS for secure connectivity between application server and RDS
=> [EXPERIMENTAL] Update CA bundle

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/maat/application.rb, app/api/datastore/entities/v1/maat/income_details.rb, app/api/datastore/entities/v1/maat/payment.rb, spec/api/datastore/entities/v1/maat/application_spec.rb
Do not sent employment income payments to MAAT
[CRIMAPP-1169](https://dsdmoj.atlassian.net/browse/CRIMAPP-1169)
[CRIMAPP-1169]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Do not send employment payments to MAAT

Gemfile, Gemfile.lock, app/models/crime_application.rb, app/services/utils/work_stream_calculator.rb, spec/models/crime_application_spec.rb, spec/services/utils/work_stream_calculator_spec.rb
Set works stream to CAT 2 where appropriate
[CRIMAPP-1069](https://dsdmoj.atlassian.net/browse/CRIMAPP-1069)
[CRIMAPP-1069]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1069?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1069] calculate work stream for self-employed

Gemfile, Gemfile.lock, app/lib/types.rb, app/services/utils/work_stream_calculator.rb, spec/services/utils/work_stream_calculator_spec.rb
Set work stream to 'non_means_tested' when  means_passport 'on_not_means_tested' .
[CRIMAPP-1183](https://dsdmoj.atlassian.net/browse/CRIMAPP-1183)
[CRIMAPP-1183]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1183 add non means tested work stream

Gemfile, Gemfile.lock
Update schema version as part of CRIMAPP-983, 984 and 985
[CRIMAPP-983](https://dsdmoj.atlassian.net/browse/CRIMAPP-983)
[CRIMAPP-984](https://dsdmoj.atlassian.net/browse/CRIMAPP-984)
[CRIMAPP-985](https://dsdmoj.atlassian.net/browse/CRIMAPP-985)
[CRIMAPP-983]: https://dsdmoj.atlassian.net/browse/CRIMAPP-983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-984]: https://dsdmoj.atlassian.net/browse/CRIMAPP-984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-985]: https://dsdmoj.atlassian.net/browse/CRIMAPP-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-983] Update schema version

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/base_application_entity.rb, app/api/datastore/entities/v1/crime_application.rb, app/api/datastore/entities/v1/pruned_application.rb, spec/api/datastore/v1/applications/list_applications_spec.rb
=> Bump schema

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/base_application_entity.rb, app/api/datastore/entities/v1/change_in_financial_circumstances_application.rb, app/api/datastore/entities/v1/pruned_application.rb, app/api/datastore/v1/applications.rb, spec/api/datastore/v1/applications/get_application_spec.rb
Introduces dedicated Application type for change in financial circumstances applications
https://dsdmoj.atlassian.net/browse/CRIMAPP-1163
Test using Apply -> New change in financial circumstances form
=> [CRIMAPP-1163] Update schema and add new type

app/api/datastore/base.rb, app/api/datastore/root.rb, app/api/datastore/v1/maat/applications.rb, app/lib/errors.rb, app/services/operations/maat/get_application.rb, spec/api/datastore/v1/maat/applications_spec.rb
Return 404 for MAAT requests for non MAAT schema compliant applications.
[CRIMAPP-573](https://dsdmoj.atlassian.net/browse/CRIMAPP-573)
[CRIMAPP-1171](https://dsdmoj.atlassian.net/browse/CRIMAPP-1171)
[CRIMAPP-573]: https://dsdmoj.atlassian.net/browse/CRIMAPP-573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CRIMAPP-1171]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1171 MAAT endpoint enforces schema contract

config/initializers/sentry.rb
Subscribe sentry and Logger to Rails.error
=> Subscribe sentry and loger to Rails.error

Gemfile, Gemfile.lock, spec/api/datastore/v1/applications/get_application_spec.rb
Updates schema, updates corresponding spec due to altered Schema fixture file
https://dsdmoj.atlassian.net/browse/CRIMAPP-1244
NA
=> [CRIMAPP-1244] Update Schema gem

app/api/datastore/entities/v1/maat/applicant.rb, app/api/datastore/entities/v1/maat/application.rb, app/api/datastore/entities/v1/maat/capital_details.rb, app/api/datastore/entities/v1/maat/case_details.rb, app/api/datastore/entities/v1/maat/client_details.rb, app/api/datastore/entities/v1/maat/income_details.rb, app/api/datastore/entities/v1/maat/means_details.rb, app/api/datastore/entities/v1/maat/outgoings_details.rb, app/api/datastore/entities/v1/maat/partner.rb, spec/api/datastore/entities/v1/maat/application_spec.rb
Make sure MAAT entity produces MAAT schema compliant json.
[CRIMAPP-1171](https://dsdmoj.atlassian.net/browse/CRIMAPP-1171)
[CRIMAPP-1171]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bring MAAT entity into line with schema

app/services/utils/maat/other_income_base.rb, spec/api/datastore/entities/v1/maat/application_spec.rb, spec/services/utils/maat/other_income_benefit_calculator_spec.rb, spec/services/utils/maat/other_income_payment_calculator_spec.rb
Once 'other' income payment is annualized and updated remove the following income payments from response
- student_loan_grant
- board_from_family
- rent
- financial_support_with_access
- from_friends_relatives
Once 'other' income benefit is annualized and updated remove the following income benefits from response
- jsa
https://dsdmoj.atlassian.net/browse/CRIMAPP-1119
=> CRIMAPP-1119 Remove annualized payments objects from response

Gemfile, Gemfile.lock
Upgrade schema to v1.2.4
https://dsdmoj.atlassian.net/browse/CRIMAPP-1119
=> Upgrade schema to v1.2.4

Gemfile, Gemfile.lock, app/services/redacting/rules.rb, spec/services/redacting/redact_spec.rb
Updates schema version and redacts arc number
https://dsdmoj.atlassian.net/browse/CRIMAPP-1181
=> [CRIMAPP-1181] Update schema v and redact arc number

Gemfile.lock, app/api/datastore/entities/v1/crime_application.rb, app/api/datastore/entities/v1/pruned_application.rb, app/api/datastore/v1/reviewing.rb, app/models/crime_application.rb, app/models/decision.rb, app/services/operations/complete_application.rb, db/migrate/20241002110620_create_decisions.rb, db/schema.rb, spec/api/datastore/entities/v1/crime_application_spec.rb, spec/api/datastore/v1/reviewing/complete_application_spec.rb, spec/models/crime_application_spec.rb
Updated the application complete route to accept an optional array of decisions created in Review, as well as a new `decisions` table to persist them.
[CRIMAPP-1355](https://dsdmoj.atlassian.net/browse/CRIMAPP-1355)
[CRIMAPP-1355]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1355] Add decisions

Gemfile, Gemfile.lock
Update to schema version that supports means decision.
=> Support means decision

db/migrate/20241022160814_allow_more_than_one_decision_per_application.rb, db/schema.rb
Support multiple decisions per Application.
=> Support multiple decisions

app/api/datastore/entities/v1/maat/income_details.rb, app/lib/transformer/maat.rb, spec/api/datastore/entities/v1/maat/application_spec.rb
Truncate manage_other_details
[CRIMAPP-1444](https://dsdmoj.atlassian.net/browse/CRIMAPP-1444)
[CRIMAPP-1444]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Truncate manage other details

app/services/operations/complete_application.rb, spec/api/datastore/v1/reviewing/complete_application_spec.rb
To be reverted after UR on 14/11
=> Temporarily disable decision validation

Gemfile, Gemfile.lock
=> Update schema to v1.4.2

Gemfile, Gemfile.lock, app/api/datastore/base.rb, app/services/operations/complete_application.rb, config/environments/test.rb, spec/api/datastore/v1/reviewing/complete_application_spec.rb, spec/rails_helper.rb
Validate decision against json schema.
https://dsdmoj.atlassian.net/browse/CRIMAPP-1435
Uses the same schema version as the original application.
=> CRIMAPP-1435 validate decisions against schema

Gemfile, Gemfile.lock, spec/api/datastore/v1/reviewing/complete_application_spec.rb
Use simplified Decision data model
=> Use simplified decision schema

Gemfile, Gemfile.lock, app/api/datastore/v1/reviewing.rb, db/migrate/20250117095032_add_court_type_and_overall_result_to_decisions.rb, db/schema.rb, spec/api/datastore/v1/reviewing/complete_application_spec.rb
Add overall_result and case_type to decisions
[CRIMAPP-1577](https://dsdmoj.atlassian.net/browse/CRIMAPP-1577)
[CRIMAPP-1577]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1577 store court_type and overall_result for decisions

Gemfile, Gemfile.lock, app/api/datastore/v1/reviewing.rb, db/migrate/20250206144354_change_decisions_court_type_to_assessment_rules.rb, db/schema.rb, spec/api/datastore/v1/reviewing/complete_application_spec.rb
Rename court_type assessment_rules. Update to use the latest schema
[CRIMAPP-1630](https://dsdmoj.atlassian.net/browse/CRIMAPP-1630)
[CRIMAPP-1630]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CRIMAPP-1630 rename court_type assessment_rules and use latest schema

Gemfile, Gemfile.lock, app/api/datastore/root.rb, openapi.json
Adds swagger/open api documentation json file 
https://dsdmoj.atlassian.net/browse/CRIMAPP-1608
=> [CRIMAPP-1608] Add open api documentation

app/models/sorting.rb, spec/models/sorting_spec.rb
Allow sorting Application Status alphabetically
[CRIMAPP-1585](https://dsdmoj.atlassian.net/browse/CRIMAPP-1585)
[CRIMAPP-1585]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1585] allow sorting by application status

Gemfile, Gemfile.lock, app/api/datastore/entities/v1/base_application_entity.rb, app/api/datastore/entities/v1/maat/application.rb, spec/api/datastore/entities/v1/crime_application_spec.rb, spec/api/datastore/entities/v1/post_submission_evidence_application_spec.rb, spec/models/crime_application_spec.rb
Include `review_status` in application details.
[CRIMAPP-1653](https://dsdmoj.atlassian.net/browse/CRIMAPP-1653)
[CRIMAPP-1653]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1653] include review status

app/services/redacting/metadata_wrapper.rb, spec/services/operations/return_application_spec.rb, spec/services/redacting/redact_spec.rb
=> [CRIMAPP-1773] add work stream to metabase

app/api/datastore/v1/applications.rb, app/api/datastore/v1/documents.rb, app/api/datastore/v1/searching.rb, config/initializers/simple_jwt_auth.rb, config/kubernetes/staging/deployment.tpl, spec/api/datastore/v1/applications/archive_application_spec.rb, spec/api/datastore/v1/applications/create_application_spec.rb, spec/api/datastore/v1/applications/get_application_spec.rb, spec/api/datastore/v1/applications/list_applications_spec.rb, spec/api/datastore/v1/documents/delete_spec.rb, spec/api/datastore/v1/documents/list_spec.rb, spec/api/datastore/v1/documents/presign_download_spec.rb, spec/api/datastore/v1/documents/presign_upload_spec.rb, spec/api/datastore/v1/searching/search_by_name_and_reference_spec.rb
Allow connection from Crime Apply Preprod
[CRIMAPP-1884](https://dsdmoj.atlassian.net/browse/CRIMAPP-1884)
[CRIMAPP-1884]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1884] allow connection from Crime Apply Preprod

Gemfile.lock
Update thor to 1.4.0 from 1.3.2
[CRIMAPP-1861](https://dsdmoj.atlassian.net/browse/CRIMAPP-1861)
[CRIMAPP-1861]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update thor to 1.4.0 from 1.3.2

Gemfile, Gemfile.lock, applying/lib/applying.rb, config/application.rb, config/initializers/event_store.rb, config/routes.rb, db/migrate/20250916115333_create_event_store_events.rb, db/schema.rb, deciding/lib/deciding.rb, deleting/lib/deleting.rb, deleting/lib/deleting/deletable.rb, reviewing/lib/reviewing.rb, spec/application_events/deleting_spec.rb, spec/rails_helper.rb
- add `rails_event_store` and `aggregate_root` dependencies
- initialize `deleting`, `applying`, `reviewing`, and `deciding` bounded contexts and events
- create `Deletable` aggregate
[CRIMAPP-1941](https://dsdmoj.atlassian.net/browse/CRIMAPP-1941)
[CRIMAPP-1941]: https://dsdmoj.atlassian.net/browse/CRIMAPP-1941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CRIMAPP-1941] Initialise Rails Event Store with bounded contexts and events
